### ISSUE TITLE
Feature request: important properties missing in ParameterDescription class

### ISSUE THREAD

**Issue by LVamos** [sunkin351/FmodAudio#1]
Could you please implement some more parameter describing properties from original library class DSP_PARAMETER_DESC? I would much appreciate these:

- [ ] DSP_PARAMETER_DESC.description
- [ ] DSP_PARAMETER_DESC.type
- [ ] DSP_PARAMETER_DESC.desc

**Comment by sunkin351** [comment]
How are you thinking I should expose `description`?
If it is the will of the community, I shall expose the `Type` field, though doing `paramDesc is FloatParameterDescription` would do just as well at this point.

Also, be advised that I am going back to the drawing board for how I expose FMOD, so that I may expose and support all existing features within the 2.0.5 release. Up to this point, I wrote this for 1.16.x.

**Comment by sunkin351** [comment]
@LVamos Can you review my numerous changes to the DSP API? I'm about to release a preview of the repository's current state.

**Comment by sunkin351** [comment]
Closing, as you now have access to the underlying struct and you can use pattern matching on the classes to determine their type.
